### ISSUE TITLE
Offseason2022: Switch tv and ty Median filter to Drivetrain.java 

### ISSUE THREAD

**Issue by reevar24** [usfirst-frc-2135/robot2022#207]
The ty filter is in Vision.java currently.

**Comment by jmullins16** [comment]
(adding comment from duplicate issue)
We should add the tv limelight filter similar to the Comp2022 C++ code. This median filter reduced the chattering of tv and stabilized the robot during shooting. The filter should reside in the drivetrain subsystem (instead of limelight subsystem like the C++ code).

Also move the ty filter into the drivetrain where it is a better fit.
